// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	file "esystem/src/pkg/utils/file"

	mock "github.com/stretchr/testify/mock"
)

// FileService is an autogenerated mock type for the FileService type
type FileService struct {
	mock.Mock
}

// Download provides a mock function with given fields: download
func (_m *FileService) Download(download file.Download) ([]byte, error) {
	ret := _m.Called(download)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(file.Download) []byte); ok {
		r0 = rf(download)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(file.Download) error); ok {
		r1 = rf(download)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFileService interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileService creates a new instance of FileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileService(t mockConstructorTestingTNewFileService) *FileService {
	mock := &FileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
